name: .NET Pull Request

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Fetch history
      run: git fetch --prune --unshallow
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
            5.0.x
            6.0.x
            8.0.x
    - name: Restore dependencies
      run: dotnet restore DotNetSiemensPLCToolBoxLibrary.sln
    - name: Build
      run: dotnet build DotNetSiemensPLCToolBoxLibrary.sln
