name: .NET

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Fetch history
      run: git fetch --prune --unshallow
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
            5.0.x
            6.0.x
            8.0.x
    - name: Restore dependencies
      run: dotnet restore DotNetSiemensPLCToolBoxLibrary.sln
    - name: Update project version
      uses: roryprimrose/set-vs-sdk-project-version@v1
      with:
        version: ${{ github.event.release.tag_name }}
        assemblyVersion: ${{ github.event.release.tag_name }}
        fileVersion: ${{ github.event.release.tag_name }}
        informationalVersion: ${{ github.event.release.tag_name }}-${{ github.sha }}
    - name: Build
      run: dotnet build --configuration Release DotNetSiemensPLCToolBoxLibrary.sln
    - uses: actions/upload-artifact@v4
      with:
        path: ./**/DotNetProjects.DotNetSiemensPLCToolBoxLibrary*.nupkg
    - name: Publish Nuget
      run: dotnet nuget push "**/DotNetProjects.DotNetSiemensPLCToolBoxLibrary*.nupkg" --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json
